sonar.projectKey=proops2026-helpdesk_frontend-react-spa
sonar.organization=proops2026-helpdesk
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.test.js,**/*.test.jsx,**/*.spec.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
