name: IaC Manual Trigger

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: "Action to perform"
        options:
          - plan
          - apply
          - destroy
        default: plan
      environment:
        type: choice
        description: "Environment"
        options:
          - lab
          - dev
          - test
          - prod
        default: lab

jobs:
  iac:
    uses: proops2026-helpdesk/cicd-platform/.github/workflows/reusable-iac.yml@v1
    with:
      action: ${{ inputs.action }}
      environment: ${{ inputs.environment }}
      working-directory: iac/${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
