{{- range $secName, $secData := $.Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secName }}
  namespace: {{ $.Values.namespace }}
  labels:
    managed-by: helm
type: Opaque
stringData:
{{- range $key, $value := $secData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
