name: PR Open — App CI

on:
  pull_request:
    paths-ignore:
      - 'iac/**'
      - '*.md'
    branches: [main]
    types: [opened, synchronize]

jobs:
  app-ci:
    uses: proops2026-helpdesk/cicd-platform/.github/workflows/reusable-app-ci.yml@v1
    with:
      runtime-version: "20"
      project-name: "proops2026"
      service-name: "ticket-service"
      image-tag: ${{ github.sha }}
      push-image: false
