apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helpdesk-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/quyet/helpdesk
    targetRevision: HEAD
    path: k8s-new/helm
    helm:
      releaseName: helpdesk-dev
      values: |
        # Override values for dev environment
        environment: dev
      valueFiles:
        - environments/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
